### ISSUE TITLE
Instructions should be collection scripts instead of a README

### ISSUE THREAD

**Issue by liberforce** [magnetikonline/linuxmicrosoftievirtualmachines#10]
Putting instructions on a README makes it hard to automake checks. You have no way of knowing when images become unavailable. I think you should instead just create a simple shell script that takes the URL of the resource to fetch, have the URLs in separate files, and test the wget return code.

This way you could easily script getting all the images and report when one is broken. Addind a new image would be as simple as putting a file on the repository.

To handle the metadata, you could just put in your data files something like:
```
IMAGE_URL=https://...
WINDOWS_VERSION_NUMBER="8.1"
WINDOWS_VERSION_NAME="Windows ${WINDOWS_VERSION_NUMBER}"
```
You source this file before calling your script, then call your script with these arguments, and you can do that in a loop.

**Comment by magnetikonline** [comment]
Good idea - but not something I have the time to play with sadly.

I will update the image URL's to correct 8/9/10 images as per your last raised issue.

This repository is going to have diminishing returns anyway - at some point MS might stop offering IE8/9/10 images anyway as those browsers finally die a death they deserve and people move onto better quality browsers.
