### ISSUE TITLE
Unable to uznip the image

### ISSUE THREAD

**Issue by AvtechScientific** [magnetikonline/linuxmicrosoftievirtualmachines#11]
I downloaded MSEdge.Win10.VirtualBox.zip directly from the MS website and try to unzip it. Bellow is what I get. Are there any md5sum or other hash values for those images, to verify whether I got errors while downloading? Thank you.

unzip MSEdge.Win10.VirtualBox.zip
Archive:  MSEdge.Win10.VirtualBox.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of MSEdge.Win10.VirtualBox.zip or
        MSEdge.Win10.VirtualBox.zip.zip, and cannot find MSEdge.Win10.VirtualBox.zip.ZIP, period.

**Comment by magnetikonline** [comment]
Which image/URL specifically?

**Comment by AvtechScientific** [comment]
I specifically need MSEdge.Win10.VirtualBox.zip . I assume I got errors
while downloading it. So could you, please, provide its md5sum or other
hash? It would be good to publish hash values for all images.

Another idea borrowed from Debian: publish torrents of the images - that
way it would be much much faster to download.

**Comment by magnetikonline** [comment]
Multiple images use `MSEdge.Win10.VirtualBox.zip` as their archive name. Need the specific version you're testing, so I can confirm/deny.

No, I can't host as torrents - these are images hosted (and owned) by Microsoft - not my place to redistribute at all.

**Comment by AvtechScientific** [comment]
I need md5sum of the following image:
MS Edge - Windows 10 Stable (16.16299)
https://github.com/magnetikonline/linuxmicrosoftievirtualmachines#ms-edge---windows-10-stable-1616299

Thank you very much! (maybe you can publish md5sums also of other images
if you have them locally).

**Comment by magnetikonline** [comment]
Just confirmed - worked fine for me and unzipped as expected

```sh
Downloaded: 2 files, 4.9G in 13m 33s (6.12 MB/s)
magnetik:/secondary/temp$ ll
total 5095332
drwxr-xr-x 2 magnetik magnetik       4096 Feb 17 14:21 ./
drwxr-xr-x 7 magnetik magnetik       4096 Dec 19 20:32 ../
-rw-r--r-- 1 magnetik magnetik 5217603343 Oct 24 06:41 MSEdge.Win10.VirtualBox.zip
-rw-r--r-- 1 magnetik magnetik         98 Feb 17 14:21 msedge-windows10-16.16299.txt
magnetik:/secondary/temp$ unzip MSEdge.Win10.VirtualBox.zip
Archive:  MSEdge.Win10.VirtualBox.zip
  inflating: MSEdge - Win10.ova      
magnetik:/secondary/temp$ md5sum MSEdge.Win10.VirtualBox.zip 
855e12de1ddc86a648ab7fe7c2ea8d4c  MSEdge.Win10.VirtualBox.zip
magnetik:/secondary/temp$ 
```

Hope that helps.
