### ISSUE TITLE
include urlhash.com torrent magnet link (with webseed)

### ISSUE THREAD

**Issue by graingert** [magnetikonline/linuxmicrosoftievirtualmachines#13]
for torrent accelerated downloads supported by the official webseed

**Comment by graingert** [comment]
eg http://www.urlhash.com/35716/MSEdge.Win10.VirtualBox.zip

**Comment by graingert** [comment]
magnet:?xt=urn:btih:d3dd5a65adedec0a6dd85ff53a7ddd7a74c93b6b&dn=MSEdge.Win10.VirtualBox.zip&ws=https%3A%2F%2Faz792536.vo.msecnd.net%2Fvms%2FVMBuild%5F20171019%2FVirtualBox%2FMSEdge%2FMSEdge.Win10.VirtualBox.zip

**Comment by graingert** [comment]
@magnetikonline ??

**Comment by magnetikonline** [comment]
Sorry @graingert probably should have given some context here. To cut to the chase, working on other projects at this time - so putting this one on the back burner I'm afraid.

Also, I feel the MS CDN is doing it's job well, with a pretty large pipe - so haven't seen the need for a Torrent invocation of these images - plus it may well violate the usage terms of these images at Microsoft's end - so don't want to raise any issues of that calibre. 

Thanks again.

**Comment by graingert** [comment]
I've needed to download these images on extremely unreliable network
connections, they usually kill TCP connections after a few minutes so
torrent is the only way to download for me

**Comment by chaoranxie** [comment]
@graingert  having same issue, current in China, is there another torrent link, MS official site takes 8 days ^__^, and i have unreliable internet

**Comment by graingert** [comment]
@chaoranxie sorry urlhash.com is down now (and probably forever). I'd recommend spinning up a free Linux instance near the Microsoft servers (eg Azure) downloading the file with aria2 and seeding it to yourself

**Comment by graingert** [comment]
@chaoranxie urlhash.com seems to be back up for me now
