### ISSUE TITLE
can't download /MSEdge.Win10.RS2.VirtualBox.zip

### ISSUE THREAD

**Issue by sibelius** [magnetikonline/linuxmicrosoftievirtualmachines#14]
wget https://az792536.vo.msecnd.net/vms/VMBuild_20170320/VirtualBox/MSEdge/MSEdge.Win10.RS2.VirtualBox.zip

anybody has this image ?

MS Edge - Windows 10 Preview (15.15063)

**Comment by alexbaumgertner** [comment]
Take a look https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by magnetikonline** [comment]
Yeah sadly @sibelius the images do come and go. I haven't had a chance to give this repo any attention for well... a while!

As per @alexbaumgertner, probably need to refer again to the public website - add new and remove dead images.

I'll leave this here as a reminder to do that.

**Comment by sibelius** [comment]
I think they removed most of them, so you have a customer that uses an old version of it, you gonna have a hard time

tks for this repo

**Comment by magnetikonline** [comment]
I'll leave this issue open, otherwise I won't see it.

You're right - it seems this whole thing might have come to a natural conclusion - which is good for the frontend HTML/CSS/JavaScript world!!

**Comment by alexbaumgertner** [comment]
I found this https://github.com/magnetikonline/linux-microsoft-ie-virtual-machines

Some images were gone but some are still there.
<img width="403" alt="Screen Shot 2020-01-30 at 08 52 42" src="https://user-images.githubusercontent.com/223620/73423708-fa528700-433d-11ea-9790-c1c6568ff226.png">
