### ISSUE TITLE
Switched default branch but not content

### ISSUE THREAD

**Issue by kingthorin** [magnetikonline/linuxmicrosoftievirtualmachines#19]
It looks as if you switched your default branch from `master` to `main` but didn't redo all your links.

Ex:
```diff
- https://github.com/magnetikonline/linuxmicrosoftievirtualmachines/raw/master/vmarchiveset/ie10-windows7.txt
+ https://github.com/magnetikonline/linuxmicrosoftievirtualmachines/raw/main/vmarchiveset/ie10-windows7.txt
```

**Comment by magnetikonline** [comment]
Thanks @kingthorin - updated in b94ba58f752032e579a512009b572117c9d3eee4.

Sadly, most of this is now gone/dead anyway - so have added a header line to note that.
