### ISSUE TITLE
IE11 - WIn10 won't boot

### ISSUE THREAD

**Issue by davetait** [magnetikonline/linuxmicrosoftievirtualmachines#4]
During boot, I get a blue screen saying "Your PC/Device needs to be repaired" and "The digital signature for this file couldn't be verified". Virtualbox version is "Version 5.1.6 r110634 (Qt5.3.2)" and installed on Debian 8 from Oracle's repository.

[screenshot](http://i.imgur.com/82SLkKN.png)

I was successfully able to run IE11 - Win8.1 earlier, so I believe my host is configured and working correctly. Host is 64-bit.

**Comment by magnetikonline** [comment]
Thanks @davetait - I'll confirm at my end... from memory I also get this problem, it might be just (sadly) a problem with Microsoft's bake of this image I'm afraid.

If that's the case - I'll add a comment to `README.md`. Unless another image exists....

**Comment by magnetikonline** [comment]
A few things on the Internet about this:
- https://connect.microsoft.com/IE/feedback/details/1326730/problem-with-windows-10-on-windows-7-virtual-box
- http://stackoverflow.com/questions/30130229/modernie-vm-windows-10-for-parallels-wont-run
- https://forums.virtualbox.org/viewtopic.php?f=2&t=68840#p330227

**Comment by magnetikonline** [comment]
Seems I had to read my own notes more!

This image has actually expired, so you need to set your host OS clock back to a time before `April 15th, 2015`. Have just retested this myself and it does work. Sadly, you need to do this every time you wish to boot the image (e.g. booting once, then rebooting with correct time will still fail the image).

Solution was here (as previously noted in `README.md`): https://connect.microsoft.com/IE/feedback/details/1326730/problem-with-windows-10-on-windows-7-virtual-box

Have made these details more prominent with ce8164b3e7dcdd2401999d930683f25c358d1323.

 Pete
