### ISSUE TITLE
For completeness

### ISSUE THREAD

**Issue by EricCote** [magnetikonline/linuxmicrosoftievirtualmachines#5]
Just for completeness, here are the links for the IE6 machines running with Windows XP. The files are still on the Microsoft servers. 

https://az412801.vo.msecnd.net/vhd/VMBuild_20141027/VirtualBox/IE6/Linux/IE6.XP.For.Linux.VirtualBox.zip.001
https://az412801.vo.msecnd.net/vhd/VMBuild_20141027/VirtualBox/IE6/Linux/IE6.XP.For.Linux.VirtualBox.zip.002

**Comment by magnetikonline** [comment]
Thanks @EricCote - well spotted, I'll get these added!

 Pete

**Comment by magnetikonline** [comment]
Thanks again @EricCote have confirmed and added as part of ecf79e202fe99a788a10d8215a304b21d182500a.
