### ISSUE TITLE
Windows 10 Enterprise (Evaluation - Build 201710) 

### ISSUE THREAD

**Issue by 2xyo** [magnetikonline/linuxmicrosoftievirtualmachines#8]
Maybe you could add "Windows 10 Enterprise (Evaluation - Build 201710) " :

- Windows 10 Fall Creators Update Enterprise Evaluation
- Visual Studio 2017 (Build 15.4) with the UWP, desktop C++, and Azure workflows enabled
- Windows developer SDK and tools (Build 16299.15, installed as part of VS UWP workflow)
- Windows UWP samples (Latest)
- Windows Subsystem for Linux enabled
- Developer mode, Bash on Ubuntu on Windows, and containers enabled

It's freely available at https://developer.microsoft.com/en-us/windows/downloads/virtual-machines  -> https://aka.ms/windev_VM_virtualbox

**Comment by magnetikonline** [comment]
The issue with these, the images timebomb after a date - rather than give 90 days from activation.

**Comment by 2xyo** [comment]
As it's only for evaluation, the expiration should not be an issue if it's well documented :) 

IMHO, it could be useful to list this VM in your repo with a warning regarding the timebomb (or you can close this issue).
