### ISSUE TITLE
Update images list

### ISSUE THREAD

**Issue by liberforce** [magnetikonline/linuxmicrosoftievirtualmachines#9]
Most of the images have been removed from the Microsoft servers, as the URL return a "Ressource not found" error. Only the Windows 10 images in your links are reachable now.

Still, there are some Win 7 and Win 8.1 images here that could be added.
https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by magnetikonline** [comment]
Yep - I'll have to update the 8/9/10 links to working copies.

Thanks for the heads up.

EDIT, paths to URI's:

```
https://az792536.vo.msecnd.net/vms/VMBuild_20150916/VirtualBox/IE8/IE8.Win7.VirtualBox.zip
https://az792536.vo.msecnd.net/vms/VMBuild_20150916/VirtualBox/IE9/IE9.Win7.VirtualBox.zip
https://az792536.vo.msecnd.net/vms/VMBuild_20150916/VirtualBox/IE10/IE10.Win7.VirtualBox.zip
https://az792536.vo.msecnd.net/vms/VMBuild_20150916/VirtualBox/IE11/IE11.Win7.VirtualBox.zip
https://az792536.vo.msecnd.net/vms/VMBuild_20171019/VirtualBox/MSEdge/MSEdge.Win10.VirtualBox.zip
```

**Comment by mgazanayi** [comment]
For IE 7, here are the official links:
```
https://download.microsoft.com/download/B/7/2/B72085AE-0F04-4C6F-9182-BF1EE90F5273/Windows_Vista_IE7.part01.exe
https://download.microsoft.com/download/B/7/2/B72085AE-0F04-4C6F-9182-BF1EE90F5273/Windows_Vista_IE7.part02.rar
https://download.microsoft.com/download/B/7/2/B72085AE-0F04-4C6F-9182-BF1EE90F5273/Windows_Vista_IE7.part03.rar
https://download.microsoft.com/download/B/7/2/B72085AE-0F04-4C6F-9182-BF1EE90F5273/Windows_Vista_IE7.part04.rar
https://download.microsoft.com/download/B/7/2/B72085AE-0F04-4C6F-9182-BF1EE90F5273/Windows_Vista_IE7.part05.rar
https://download.microsoft.com/download/B/7/2/B72085AE-0F04-4C6F-9182-BF1EE90F5273/Windows_Vista_IE7.part06.rar
```

Just rename the first .exe file to .rar and then 

`unrar e Windows_Vista_IE7.part01.rar .`

**Comment by magnetikonline** [comment]
I've made the above updates against 07fd81ee5fab317bde59cca2e076d7c178da704b.

What does this mean? The following images are now **no longer available**:

- IE6
- IE7
- IE8 - WinXP
- IE10 - Win8
- IE11 - Win10

Have to say, I'm rather disappointed by this development.

- One hand you can argue that IE6 - IE7 and Windows XP are well past their use by date and are probably a security nightmare to still be offering up/running.
- On the other hand reality _might_ say there are still front end developers that need to maintain websites or internal systems (that still do the job just fine) for users that still run these ancient browsers - or use web applications that require ActiveX, etc. and budgets don't allow for a 2018 rewrite.

Considering Microsoft were happy to tightly tie their browser to the operating system (and essentially still do), I would have thought *the least* they could do is continue to offer these time-bombed images for those poor developers that get lugged with still debugging/developing web applications against them.

I certainly still do receive the occasional email/message asking why these images "no longer work" - so people still have a (small) need for them at times. What's the harm in offering them?

If it was simply issue with cost and bandwidth of hosting these large images on their CDN (fair enough) - I'm sure another CDN provider would have been more than welcome to step in for the hosting.

Anyway, that's the way things are going forward - I'll end my rant here. :smile:
